### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by ghost** [UpsilonDev/juroku-docker#5]
ive set up the docker env, got cc dependencies, but thats where the issue is

i have no idea how to configure the video.lua monitors section

**Comment by signalhunter** [comment]
I believe this issue is out of scope of my project, but I'll help anyways...

The `monitors` table contains 4 `wrapRemote` elements that correspond to each quadrant of the screen (left-to-right, top-to-bottom).
The 2nd argument of wrapRemote is the side of an full-block modem that is connected to the monitors that you specified.
If you got an error about failing to obtain direct peripheral access, try changing the upvalue index to 1 or 3 (on line 7 of video.lua).

For example, if this is your screen setup:
```
+-----------+-----------+
|           |           |
| monitor_0 | monitor_1 |
|           |           |
+-----------+-----------+
|           |           |
| monitor_2 | monitor_3 |
|           |           |
+-----------+-----------+
```
... and a full-block modem is on the TOP of the video computer, your `monitors` table should look like this:
```lua
local monitors = {
  wrapRemote("monitor_0", "top"),
  wrapRemote("monitor_1", "top"),
  wrapRemote("monitor_2", "top"),
  wrapRemote("monitor_3", "top")
}
```

Hope that helped!
